server:
  port: 8079

logging:
  level:
    root: info
    indi.ly.crush: debug

spring:
  application:
    name: scheduled_timed_task
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: crush
    url: >
          jdbc:mysql://localhost:3306/scheduled_timed_task?
          useSSL=true&
          useUnicode=true&
          characterEncoding=UTF-8&
          useTimezone=true&
          serverTimezone=GMT%2B8&
          allowMultiQueries=true&
          rewriteBatchedStatements=true
    hikari:
      auto-commit: true
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: mysql
    open-in-view: true
    show-sql: true
    generate-ddl: false
    hibernate:
      naming:
        # CamelCaseToUnderscoresNamingStrategy: 驼峰
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true